tasks:
  - name: Gitpod Task
    before: |
      # Install JDK
      echo "Installing JDK ..."
      sdk install java 17.0.4.1-tem < /dev/null

      echo "Build gradle for '$path' ..."
      chmod +x gradlew*
      ./gradlew bootJar

    command: |
      # Check if environment variables are set in https://gitpod.io/variables.
      echo "Checking if environment variables are set ..."
      if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
        echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
        exit 1
      fi

      # Run the application based on specified $path.
      echo "Starting application for '$path' in $(pwd)"
      ./gradlew bootRun

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
